name: CI

on:
  push:
    branches:
      - master

env:
  IMAGE: ${{secrets.DOCKER_HUB_USERNAME}}/simpleapp:latest
  HEROKU_APP_NAME: simpleapp

jobs:

  push-telegram-job:
    name: Push Notification Job
    runs-on: ubuntu-latest
    steps:
      - name: Get commit message
        run: |
          commit_hash=$(git log -1 --pretty=format:%h)
          commit_msg=$(git log -1 --pretty=format:%s)
          echo "Commit $commit_hash: $commit_msg"
      - name: Send message to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ env.TELEGRAM_CHAT_ID }}
          token: ${{ env.TELEGRAM_BOT_TOKEN }}
          message: "Push realizado na master! Commit $commit_hash: $commit_msg"

  build-job:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{env.IMAGE}}
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}

  test-job:
    name: SAST Scan
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run SAST Scan
        uses: AppThreat/sast-scan-action@master
        with:
          type: "python"
          target: .
          report_file: sast_report.json

  deploy-job:
    name: Deploy Job
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - name: Login to Heroku
        run: heroku container:login
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      - name: Push Docker image to Heroku
        run: |
          docker tag $DOCKER_USERNAME/$IMAGE:latest registry.heroku.com/$HEROKU_APP_NAME/web
          docker push registry.heroku.com/$HEROKU_APP_NAME/web
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      - name: Release Docker image to Heroku
        run: heroku container:release web --app $HEROKU_APP_NAME
      - name: Display App URL
        run: |
          echo "App URL: https://$HEROKU_APP_NAME.herokuapp.com"
    
  deploy-telegram-job:
    name: Deploy Notification Job
    runs-on: ubuntu-latest
    steps:
    - name: Send message to Telegram
      uses: appleboy/telegram-action@v2.3.1
      with:
        to: ${{secrets.TELEGRAM_CHAT_ID}}
        token: ${{secrets.TELEGRAM_BOT_TOKEN}}
        message: "Deploy realizado!"
